global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "order service"
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ["localhost:8084"]
